id: P69E2A9E2
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN10210
  title: རྣལ་འབྱོར་བླ་མེད་ཀྱི་སྒྲུབ་ཐབས་དང་བསྐྱེད་རིམ་གྱི་ཁྲིད་ཡིག་ཁག
  volumes:
    9c713fef910741e987d0873eb7b40f46:
      image_group_id: I3CN10212
      title: ''
      base_file: v001.txt
  author: ''
